version: '3.8'

services:
  kafka:
    image: apache/kafka:3.7.1
    hostname: kafka
    container_name: kafka
    environment:
      KAFKA_KRAFT_MODE: "true"
      KAFKA_PROCESS_ROLES: "broker,controller"
      KAFKA_NODE_ID: 1
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka:9093"
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,EXTERNAL://0.0.0.0:9192,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,EXTERNAL://localhost:9192
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LOG_DIRS: /var/lib/kafka/data
      CLUSTER_ID: "12kGGeoWTqOtmFmYI0aKOA"
    volumes:
      - ./data/kafka:/var/lib/kafka/data
    ports:
      - "9092:9092"   # Internal for other containers
      - "9192:9192"   # External for host access
      - "9093:9093"   # Controller
    networks:
      - kafka-net

networks:
  kafka-net:
    driver: bridge
